# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 181504a82bf60f1a789ef6754e5f4c6d1f03a6d9b08bbd9957d1350835e580ad4b1055d456421368b4078dbc3b4ae9dc259a547ff8817ebf3ee4e3b7efbf67ce

test:
  secret_key_base: 04bfd779bf8909f7029f0fb98fcdf146a6a4b8b56ac2b6196778e9037c42cc32ce6e9bbf6ecab51e424e586473cd0da11ce99be3a5429f22d6d73152ed32e299

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
